<a href="https://colab.research.google.com/github/mahalak2004/Machine-learning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# -----------------------------------
# Step 1: Collect data from user
# 5 students, 4 subjects (or attributes)
# -----------------------------------
data = []

print("Enter marks for 5 students in 4 subjects (space-separated):")
for i in range(5):
    row = list(map(float, input(f"Student {i+1}: ").split()))
    if len(row) != 4:
        print("Error: Enter exactly 4 numbers")
        exit()
    data.append(row)

data = np.array(data)

print("\nSTEP 1: ORIGINAL DATASET")
print(data)

# -----------------------------------
# Step 2: Compute mean
# -----------------------------------
mean = np.mean(data, axis=0)
print("\nSTEP 2: MEAN OF EACH ATTRIBUTE")
print(mean)

# -----------------------------------
# Step 3: Mean-center the data
# -----------------------------------
centered_data = data - mean
print("\nSTEP 3: MEAN-CENTERED DATA")
print(centered_data)

# -----------------------------------
# Step 4: Covariance matrix
# -----------------------------------
cov_matrix = np.cov(centered_data.T)  # columns = variables
print("\nSTEP 4: COVARIANCE MATRIX")
print(cov_matrix)

# -----------------------------------
# Step 5: Eigenvalues and Eigenvectors
# -----------------------------------
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nSTEP 5: EIGENVALUES")
print(eigenvalues)
print("\nSTEP 5: EIGENVECTORS")
print(eigenvectors)

# -----------------------------------
# Step 6: Explained Variance (%)
# -----------------------------------
total_variance = np.sum(eigenvalues)
explained_variance = (eigenvalues / total_variance) * 100
print("\nSTEP 6: EXPLAINED VARIANCE (%)")
print(explained_variance)

# -----------------------------------
# Step 7: Minimum components to retain >=90% variance
# -----------------------------------
sorted_index = np.argsort(eigenvalues)[::-1]  # descending
sorted_variance = explained_variance[sorted_index]
cumulative_variance = np.cumsum(sorted_variance)
num_components = np.where(cumulative_variance >= 90)[0][0] + 1

print("\nMINIMUM NUMBER OF COMPONENTS REQUIRED")
print(num_components)

# -----------------------------------
# Step 8: Project data onto top principal components
# -----------------------------------
selected_vectors = eigenvectors[:, sorted_index[:num_components]]
reduced_data = centered_data.dot(selected_vectors)

print("\nSTEP 8: REDUCED DATASET")
print(reduced_data)

print("\nTOTAL VARIANCE RETAINED (%)")
print(cumulative_variance[num_components - 1])

Enter marks for 5 students in 4 subjects (space-separated):
Student 1: 98 88 75 89
Student 2: 78 65 99 84
Student 3: 66 72 96  55
Student 4: 88 75 68 92
Student 5: 99 88 77 55

STEP 1: ORIGINAL DATASET
[[98. 88. 75. 89.]
 [78. 65. 99. 84.]
 [66. 72. 96. 55.]
 [88. 75. 68. 92.]
 [99. 88. 77. 55.]]

STEP 2: MEAN OF EACH ATTRIBUTE
[85.8 77.6 83.  75. ]

STEP 3: MEAN-CENTERED DATA
[[ 12.2  10.4  -8.   14. ]
 [ -7.8 -12.6  16.    9. ]
 [-19.8  -5.6  13.  -20. ]
 [  2.2  -2.6 -15.   17. ]
 [ 13.2  10.4  -6.  -20. ]]

STEP 4: COVARIANCE MATRIX
[[ 195.2   116.9  -148.     67.5 ]
 [ 116.9   103.3   -95.25  -27.  ]
 [-148.    -95.25  187.5   -90.75]
 [  67.5   -27.    -90.75  341.5 ]]

STEP 5: EIGENVALUES
[476.45201025 296.42186304  43.34356827  11.28255843]

STEP 5: EIGENVECTORS
[[ 0.53828987  0.36621767 -0.58281422 -0.48626764]
 [ 0.26594777  0.45187088 -0.1670806   0.83496621]
 [-0.54668298 -0.24702824 -0.78577444  0.15057654]
 [ 0.58365531 -0.77503185 -0.12235271  0.20905006]]

STEP 6: EXPLA